// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnX4uJJdqfwCcUk11nyLuAI16frLpB01E',
    appId: '1:526041151558:web:af95f64a1af9bc76253247',
    messagingSenderId: '526041151558',
    projectId: 'insti-app-iitm',
    authDomain: 'insti-app-iitm.firebaseapp.com',
    storageBucket: 'insti-app-iitm.appspot.com',
    measurementId: 'G-SWLF262JD7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgxTgnSEtdXhABKXX6qFoQlKAW1o8dXrU',
    appId: '1:526041151558:android:9614eeac8c45555b253247',
    messagingSenderId: '526041151558',
    projectId: 'insti-app-iitm',
    storageBucket: 'insti-app-iitm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2XvVb7Z9AYk1KhB4AwEXgm-I7UFu7oMc',
    appId: '1:526041151558:ios:56d076b35b5f68dc253247',
    messagingSenderId: '526041151558',
    projectId: 'insti-app-iitm',
    storageBucket: 'insti-app-iitm.appspot.com',
    androidClientId: '526041151558-61lpstlt0iqjmurv79s6aag3h6enu3ul.apps.googleusercontent.com',
    iosClientId: '526041151558-ak08o7fqkfdk9kb3k8nt17pf9bgev5ul.apps.googleusercontent.com',
    iosBundleId: 'com.example.instiAppDevStuff',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2XvVb7Z9AYk1KhB4AwEXgm-I7UFu7oMc',
    appId: '1:526041151558:ios:56d076b35b5f68dc253247',
    messagingSenderId: '526041151558',
    projectId: 'insti-app-iitm',
    storageBucket: 'insti-app-iitm.appspot.com',
    androidClientId: '526041151558-61lpstlt0iqjmurv79s6aag3h6enu3ul.apps.googleusercontent.com',
    iosClientId: '526041151558-ak08o7fqkfdk9kb3k8nt17pf9bgev5ul.apps.googleusercontent.com',
    iosBundleId: 'com.example.instiAppDevStuff',
  );
}
